# .github/workflows/cypress-pipeline.yml
name: Run Basic Cypress Tests

# Em que momento será executada
on:
  pull_request:
    branches: [master]

# jobs que irao rodar na pipeline
# só temos um que vai rodar os testes do cypress
jobs:
  cypress-run:
    # maquina que ira rodar a pipeline
    runs-on: ubuntu-latest

    # Passos que serao executados
    steps:
      # clone do projeto
      - name: checkout/clone do projeto
        uses: actions/checkout@v4

      # exemplo de execução no terminal
      - name: instalar dependências do projeto
        run: echo Mateus

      # execução e configuraçao do projeto
      - name: Run testes
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          
      # upload do relatório do mocha
      - name: Upload relatório do mocha
        uses: actions/upload-artifact@v4
        with:
          name: relatorio
          path: cypress\reports\html